---
- name: Handler
  hosts: all
  become: true
  become_method: sudo
  connection: ssh
  ignore_errors: false
  tasks:
    - name: Handler task
      paskage:
       name: httpd
       state: latest
      notify: HTTPD RESTART
   - name: Install mysql
  
  
  
  
   paskage:
   name: mariadb-server
   state: present
   notify: MYSQL RESTART
    
 
 
 
  handlers:
    - name: HTTPD RESTART
      systemd: 
       name: httpd
       state: restarted
